name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Ensures the job runs on a Windows machine

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python (Make sure you're using the right Python version)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies (including PyInstaller)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      # Step 4: Build the EXE using PyInstaller
      - name: Build EXE
        run: |
          pyinstaller --onefile --collect-all Automate_Data_Updates.py

      # Step 5: Check contents of dist folder
      - name: List contents of dist folder
        run: |
          echo "Checking contents of dist folder:"
          dir dist/

      # Step 6: Upload EXE file as an artifact (use actions/upload-artifact@v3)
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: Automate_Data_Updates.exe
          path: dist/Automate_Data_Updates.exe

